name: Deploy

on:
  pull_request:
  branches: [ master ]
  
jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
        working-directory: ./dist
      - run: git init
      - run: git add -A
      - run: git commit -m 'deploy'
      - run: git push -f git@github.com:Maciejowski2006/unity-quiz.git master:gh-pages